In [1]:
import numpy as np

In [85]:
print(np.__version__)

1.18.1


In [67]:
a=np.array((1,2,3,4))

In [68]:
a

array([1, 2, 3, 4])

In [69]:
b = np.arange(10).reshape(2, 5)

In [70]:
b

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [4]:
b.shape

(2, 5)

In [7]:
b.ndim

2

In [8]:
b.dtype

dtype('int32')

In [9]:
b.itemsize

4

In [11]:
b.size

10

In [12]:
type(b)

numpy.ndarray

In [13]:
np.zeros((7, 5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [15]:
np.ones((5, 4,5))

array([[[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]]])

In [16]:
np.empty( (2,3) )

array([[0., 0., 0.],
       [0., 0., 0.]])

In [21]:
np.arange( 3, 40,4 )

array([ 3,  7, 11, 15, 19, 23, 27, 31, 35, 39])

In [71]:
c=np.array((3,6,4,7,1,19,2))

In [72]:
c

array([ 3,  6,  4,  7,  1, 19,  2])

In [73]:
d=np.array((6,1,12,8,2,7,11))

In [74]:
d

array([ 6,  1, 12,  8,  2,  7, 11])

In [27]:
c-d

array([-3,  5, -8, -1, -1, 12, -9])

In [28]:
c*d

array([ 18,   6,  48,  56,   2, 133,  22])

In [30]:
np.sin(d)

array([-0.2794155 ,  0.84147098, -0.53657292,  0.98935825,  0.90929743,
        0.6569866 , -0.99999021])

In [31]:
A = np.array( [[1,1],[0,1]] )

In [32]:
B = np.array( [[2,0],[3,4]] )

In [33]:
A * B   

array([[2, 0],
       [0, 4]])

In [34]:
A @ B  

array([[5, 4],
       [3, 4]])

In [35]:
A.dot(B) 

array([[5, 4],
       [3, 4]])

In [39]:
e = np.ones(3, dtype=np.int32)

In [42]:
f = np.linspace(0,3)

In [43]:
f.dtype.name

'float64'

In [46]:
g =np.e+f

In [47]:
g

array([2.71828183, 2.77950632, 2.84073081, 2.9019553 , 2.96317979,
       3.02440428, 3.08562877, 3.14685326, 3.20807775, 3.26930224,
       3.33052673, 3.39175122, 3.45297571, 3.5142002 , 3.57542469,
       3.63664918, 3.69787367, 3.75909815, 3.82032264, 3.88154713,
       3.94277162, 4.00399611, 4.0652206 , 4.12644509, 4.18766958,
       4.24889407, 4.31011856, 4.37134305, 4.43256754, 4.49379203,
       4.55501652, 4.61624101, 4.6774655 , 4.73868999, 4.79991448,
       4.86113897, 4.92236346, 4.98358795, 5.04481244, 5.10603693,
       5.16726142, 5.22848591, 5.2897104 , 5.35093489, 5.41215938,
       5.47338387, 5.53460836, 5.59583285, 5.65705734, 5.71828183])

In [48]:
g.dtype.name

'float64'

In [49]:
h = np.exp(c*1j)

In [50]:
h

array([-0.9899925 +0.14112001j,  0.96017029-0.2794155j ,
       -0.65364362-0.7568025j ,  0.75390225+0.6569866j ,
        0.54030231+0.84147098j,  0.98870462+0.14987721j,
       -0.41614684+0.90929743j])

In [51]:
h.dtype.name

'complex128'

In [75]:
x = np.arange(10)**3

In [76]:
x

array([  0,   1,   8,  27,  64, 125, 216, 343, 512, 729], dtype=int32)

In [53]:
x[2]

8

In [54]:
x[2:5]

array([ 8, 27, 64], dtype=int32)

In [77]:
x[:6:2] = 1000  

In [78]:
x

array([1000,    1, 1000,   27, 1000,  125,  216,  343,  512,  729],
      dtype=int32)

In [56]:
x[ : :-1]

array([ 729,  512,  343,  216,  125, 1000,   27, 1000,    1, 1000],
      dtype=int32)

In [57]:
def f(x,y):
    return 10*x+y

In [80]:
z = np.fromfunction(f,(5,4),dtype=int)              

In [79]:
z

array([[ 0,  1,  2,  3],
       [10, 11, 12, 13],
       [20, 21, 22, 23],
       [30, 31, 32, 33],
       [40, 41, 42, 43]])

In [59]:
z[2,3]

23

In [60]:
z[0:5, 1]                       

array([ 1, 11, 21, 31, 41])

In [61]:
z[ : ,1] 

array([ 1, 11, 21, 31, 41])

In [62]:
z[1:3, : ] 

array([[10, 11, 12, 13],
       [20, 21, 22, 23]])

In [82]:
arr = np.arange(15) 

In [83]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])