In [1]:
import numpy as np

In [2]:
a=np.array((1,2,3,4))
a

array([1, 2, 3, 4])

In [3]:
b = np.arange(10).reshape(2, 5)
b

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [4]:
b.shape

(2, 5)

In [7]:
b.ndim

2

In [8]:
b.dtype

dtype('int32')

In [9]:
b.itemsize

4

In [11]:
b.size

10

In [12]:
type(b)

numpy.ndarray

In [13]:
np.zeros((7, 5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [15]:
np.ones((5, 4,5))

array([[[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]]])

In [16]:
np.empty( (2,3) )

array([[0., 0., 0.],
       [0., 0., 0.]])

In [21]:
np.arange( 3, 40,4 )

array([ 3,  7, 11, 15, 19, 23, 27, 31, 35, 39])